import type { Metadata } from "next";
import { Lora, Cormorant_SC } from "next/font/google";
import "./globals.css";

const lora = Lora({
  variable: "--font-lora-sans",
  subsets: ["latin"],
});

const cormorant = Cormorant_SC({
  variable: "--font-cormorant-sc",
    subsets: ["latin"],
    weight: "700"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${cormorant.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
